@extends('layouts.app')

@php($editing = $branch->exists)
@section('title', $editing ? 'تعديل الفرع' : 'إضافة فرع')

@section('content')
    <div class="mx-auto max-w-4xl space-y-6">
        <div class="flex items-center justify-between gap-4"><div><a href="{{ route('business.branches.index') }}" class="inline-flex items-center gap-1 text-sm font-bold text-indigo-600 hover:underline"><i class="bx bx-arrow-forward" aria-hidden="true"></i>الفروع</a><p class="mt-4 text-sm font-bold text-indigo-600">إدارة الفروع</p><h1 class="mt-2 text-3xl font-extrabold text-slate-900">{{ $editing ? 'تعديل بيانات الفرع' : 'إضافة فرع جديد' }}</h1></div></div>
        @if ($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert"><p class="font-bold">يرجى مراجعة البيانات التالية:</p><ul class="mt-2 list-disc space-y-1 pr-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
            <form method="POST" action="{{ $editing ? route('business.branches.update', $branch) : route('business.branches.store') }}" class="grid gap-5 md:grid-cols-2">@csrf @if($editing) @method('PUT') @endif
                <div><label for="branch-name" class="text-sm font-bold text-slate-700">اسم الفرع</label><input id="branch-name" name="name" value="{{ old('name', $branch->name) }}" required autocomplete="organization" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-slate-900 shadow-sm outline-none transition placeholder:text-slate-400 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></div>
                <div><label for="branch-code" class="text-sm font-bold text-slate-700">رمز الفرع</label><input id="branch-code" name="code" value="{{ old('code', $branch->code) }}" required autocomplete="off" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 font-mono text-slate-900 shadow-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"><p class="mt-1 text-xs text-slate-500">أحرف إنجليزية وأرقام وشرطة وشرطة سفلية.</p></div>
                <div><label for="branch-phone" class="text-sm font-bold text-slate-700">الهاتف</label><input id="branch-phone" name="phone" value="{{ old('phone', $branch->phone) }}" autocomplete="tel" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-slate-900 shadow-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></div>
                <div><label for="branch-email" class="text-sm font-bold text-slate-700">البريد الإلكتروني</label><input id="branch-email" type="email" name="email" value="{{ old('email', $branch->email) }}" autocomplete="email" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-left text-slate-900 shadow-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></div>
                <div class="md:col-span-2"><label for="branch-address" class="text-sm font-bold text-slate-700">العنوان</label><input id="branch-address" name="address_line_1" value="{{ old('address_line_1', $branch->address_line_1) }}" autocomplete="street-address" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-slate-900 shadow-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></div>
                <div><label for="branch-city" class="text-sm font-bold text-slate-700">المدينة</label><input id="branch-city" name="city" value="{{ old('city', $branch->city) }}" autocomplete="address-level2" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-slate-900 shadow-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></div>
                <div><label for="branch-state" class="text-sm font-bold text-slate-700">المنطقة / المحافظة</label><input id="branch-state" name="state" value="{{ old('state', $branch->state) }}" autocomplete="address-level1" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-slate-900 shadow-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></div>
                <div><label for="branch-country" class="text-sm font-bold text-slate-700">الدولة</label><input id="branch-country" name="country_code" value="{{ old('country_code', $branch->country_code ?: 'EG') }}" maxlength="2" autocomplete="country" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 uppercase text-slate-900 shadow-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></div>
                <div><label for="branch-timezone" class="text-sm font-bold text-slate-700">المنطقة الزمنية</label><input id="branch-timezone" name="timezone" value="{{ old('timezone', $branch->timezone ?: 'Africa/Cairo') }}" required autocomplete="off" class="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-slate-900 shadow-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></div>
                <div class="md:col-span-2"><button class="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-6 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-indigo-700 focus:outline-none focus:ring-4 focus:ring-indigo-200"><i class="bx bx-save" aria-hidden="true"></i>حفظ الفرع</button></div>
            </form>
        </div>
        @if($editing)
            <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div class="flex items-center justify-between gap-3"><div><h2 class="text-xl font-extrabold text-slate-900">تعيينات الفريق</h2><p class="mt-1 text-sm text-slate-500">يملك المالك وصولاً تلقائياً لكل الفروع النشطة.</p></div>@if($branch->isActive())<span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">نشط</span>@endif</div>
                @if($branch->isActive())<form method="POST" action="{{ route('business.branches.assignments.store', $branch) }}" class="mt-5 flex flex-col gap-3 sm:flex-row">@csrf<select name="user_id" required aria-label="اختر عضواً لإسناده" class="h-12 flex-1 rounded-xl border border-slate-300 bg-white px-4 shadow-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"><option value="">اختر عضواً لإسناده</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} — {{ $user->email }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white hover:bg-slate-800 focus:outline-none focus:ring-4 focus:ring-slate-200">تفعيل التعيين</button></form>@endif
                <div class="mt-5 divide-y divide-slate-100">@forelse($branch->assignments as $assignment)<div class="flex items-center justify-between gap-3 py-3"><div><p class="font-semibold">{{ $assignment->user->name }}</p><p class="text-xs text-slate-500">{{ $assignment->user->email }}</p></div><div class="flex items-center gap-2"><span class="text-xs font-bold {{ $assignment->isActive() ? 'text-emerald-600' : 'text-slate-400' }}">{{ $assignment->isActive() ? 'نشط' : 'غير نشط' }}</span>@if($assignment->isActive())<form method="POST" action="{{ route('business.branches.assignments.destroy', [$branch, $assignment->user]) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-red-600 hover:underline">تعطيل</button></form>@else<form method="POST" action="{{ route('business.branches.assignments.update', [$branch, $assignment->user]) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="active"><button class="text-xs font-bold text-indigo-600 hover:underline">تفعيل</button></form>@endif</div></div>@empty<p class="py-4 text-sm text-slate-500">لا توجد تعيينات لهذا الفرع.</p>@endforelse</div>
            </div>
            @if($branch->isActive() && ($branchesCount ?? 2) > 1)<form method="POST" action="{{ route('business.branches.deactivate', $branch) }}" class="mt-6">@csrf<button class="rounded-xl border border-red-200 px-4 py-3 text-sm font-bold text-red-600 hover:bg-red-50 focus:outline-none focus:ring-4 focus:ring-red-100">تعطيل الفرع</button></form>@endif
        @endif
    </div>
@endsection
